name: Run Google Cloud Function Framework

on:
  workflow_dispatch:
    inputs:
      input_from_postman:
        description: 'Input from Postman'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

      - name: Run Google Cloud Function Framework with Input
        env:
          INPUT_FROM_POSTMAN: ${{ github.event.inputs.input_from_postman }}
        run: |
          npx @google-cloud/functions-framework --target=textexecutor --input "${INPUT_FROM_POSTMAN}"
